services:
  postgres:
    image: postgres:16-alpine
    container_name: yourproject_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lolbet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yourdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:yourpassword
  postgres_data:
    driver: local